apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jfj10exme-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jfj10exme-python 
  name: jfj10exme-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jfj10exme-python 
